/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from "react";
import {
  Platform,
  StyleSheet,
  Text,
  View,
  TouchableOpacity
} from "react-native";
import CBCanvasWidget from "react-native-canvas-widget";

export default class App extends Component<{}> {
  states = [
    '[{"name":"fillStyle","value":["#00FFbb"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#FF0000"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#00FF00"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#0000ff"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#00FFbb"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#FF0000"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#00FF00"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#0000ff"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#00FFbb"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#FF0000"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#00FF00"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#0000ff"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#00FFbb"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#FF0000"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#00FF00"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#0000ff"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#00FFbb"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#FF0000"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#00FF00"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]',
    '[{"name":"fillStyle","value":["#0000ff"]},{"name":"fillRect","value":[0, 0, 300, 150]},{"name":"clearRect","value":[20, 20, 100, 50]}]'
  ];

  constructor(props) {
    super(props);
    this.state = {
      activeIndex: 0,
      counter: 0
    };
  }

  componentDidMount() {
    setInterval(() => {
      if (this.state.activeIndex < this.states.length) {
        this.setState({
          activeIndex: this.state.activeIndex + 1,
          counter: this.state.counter + 1
        });
      } else {
        this.setState({
          activeIndex: 0,
          counter: this.state.counter + 1
        });
      }
    }, 240);
  }

  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity
          onPress={() => {
            this.setState({ counter: this.state.counter + 1 });
          }}
        >
          <Text>sadsad {this.state.counter}</Text>
        </TouchableOpacity>
        <CBCanvasWidget
          onChange={() => {
            this.setState({ counter: this.state.counter + 1 });
          }}
          style={{ width: 200, height: 200 }}
          commands={this.states[this.state.activeIndex]}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10
  },
  instructions: {
    textAlign: "center",
    color: "#333333",
    marginBottom: 5
  }
});
