/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from "react";
import { Platform, StyleSheet, Text, View } from "react-native";
import CBCanvasWidget from "react-native-canvas-widget";

export default class App extends Component<{}> {
  render() {
    return (
      <View style={styles.container}>
        <CBCanvasWidget
          commands={
            '[{"name":"beginPath","value":[]},{"name":"lineWidth","value":[5]},{"name":"strokeStyle","value":["#00ee1c"]},{"name":"moveTo","value":[20,20]},{"name":"bezierCurveTo","value":[20,100,200,100,200,20]},{"name":"quadraticCurveTo","value":[20,100,200,20]},{"name":"rect","value":[20,20,350,300]},{"name":"arc","value":[100,75,50,0,6.283185307179586]},{"name":"stroke","value":[]}]'
          }
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10
  },
  instructions: {
    textAlign: "center",
    color: "#333333",
    marginBottom: 5
  }
});
